### ISSUE TITLE
Arreglar sección de Ponentes

### ISSUE THREAD

**Issue by skcode7** [javascriptecuador/WoJS2021#1]
Colocar las imágenes de los participantes confirmados.
Sería interesante que al dar clic o poner el cursos sobre la imagen se despliegue la información detallada.

Quiero hacerme cargo de esta parte ✋🏼

**Comment by rpalaciosg** [comment]
dale Carlos, de una

**Comment by rpalaciosg** [comment]
Una consulta, tienen algun problema al ejecutar el comando `gulp` ?

**Comment by skcode7** [comment]
Me da un error
![imagen](https://user-images.githubusercontent.com/55223838/119753009-aa1d0380-be63-11eb-9c03-e19cb1dbcedf.png)


Y al revisar el **gulfile** el editor me marca error en la parte de la tarea default
![imagen](https://user-images.githubusercontent.com/55223838/119753077-c3be4b00-be63-11eb-9852-49cdd51331f7.png)

**Comment by rpalaciosg** [comment]
dale, por tiempo modifiquemos el dist, luego minificamos el html y el css que se agregue.
